name: Monetary
main: me.pandemic.monetary.Monetary
version: 0.1
description: >
             An economy plugin for bukkit
commands:
    balance:
        description: Check your balance
    addmoney:
        description: Adds money to a players account